# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 161e7a8b2733ad8460a6e3b1f55ccea0df61ef562749b9f6c8d7ec2433ec9d30801a728a0342013f442b438120ddfde2c6483e7733c8922e07c967dde9fe9071

test:
  secret_key_base: feb296a5a8a017c202096abf2541b56d4bfdd2048511c72f432bdef7ce51d903e06e0b6fda89205fbdf02355de9a819867d8c7a00bbd42e7baad94bb66f31294

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
